# Generated by Django 3.0.5 on 2020-04-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.TextField(max_length=500)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
